# Generated by Django 6.0 on 2026-06-04 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_aggregated_hour', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('section', models.CharField(max_length=50)),
                ('total_requests', models.IntegerField()),
                ('unique_visitors', models.IntegerField()),
                ('unique_visitors_hll', models.BinaryField()),
            ],
            options={
                'unique_together': {('period_start', 'section')},
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('section', models.CharField(db_index=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'section'], name='metrics_raw_timesta_efb580_idx')],
            },
        ),
    ]
