# Generated by Django 6.0 on 2026-06-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyaggregate',
            name='unique_visitors_hll',
        ),
    ]
