# Generated by Django 6.0 on 2026-03-23 13:06

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_supervisorprofile_academic_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latex_file', models.FileField(upload_to=documents.models.template_upload_path)),
                ('name_template', models.CharField(blank=True, help_text='e.g. Registration Form - {name}', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/generated/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fully_signed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/template_assets/')),
                ('name', models.CharField(help_text='Filename used inside LaTeX (e.g. logo.png or style.sty)', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('signature', 'Signature')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('computed_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='template_fields', to='authentication.role')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('signature_salt', models.CharField(blank=True, max_length=128, null=True)),
                ('signature', models.CharField(blank=True, max_length=128, null=True)),
                ('blob_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='documents.generateddocument')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.templatefield')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_blob', models.TextField(blank=True, null=True)),
                ('signature_salt', models.CharField(blank=True, max_length=128, null=True)),
                ('attestation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.attestation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.generateddocument')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.templatefield')),
            ],
            options={
                'unique_together': {('document', 'field')},
            },
        ),
    ]
