# Generated by Django 6.0 on 2026-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('choice', 'Choice'), ('boolean', 'Boolean'), ('signature', 'Signature')], max_length=50),
        ),
    ]
