# Generated by Django 6.0 on 2026-03-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_templatefield_choices_alter_templatefield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='computed_expression',
        ),
    ]
