# Generated by Django 6.0 on 2026-03-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_templatefield_computed_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='order',
        ),
    ]
