# Generated by Django 6.0 on 2026-04-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_templatefield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
