# Generated by Django 6.0 on 2026-04-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_generateddocument_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddocument',
            name='is_fully_signed',
        ),
    ]
