# Generated by Django 6.0 on 2026-04-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0009_application_accepted_at'),
        ('documents', '0006_remove_generateddocument_is_fully_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='astrolink.application'),
        ),
    ]
