# Generated by Django 6.0 on 2026-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_generateddocument_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
