# Generated by Django 6.0 on 2026-05-31 12:01

import documents.models
import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documenttemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=documents.storage.PrivateMediaStorage(), upload_to=documents.models.private_upload_path),
        ),
    ]
