# Generated by Django 6.0 on 2026-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_generateddocument_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
