# Generated by Django 6.0 on 2026-01-04 18:45

import astrolink.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=64)),
                ('contact_name', models.CharField(max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('UNDER_CONTRACT', 'Under Contract (DO NOT CONTACT)'), ('EXTERN_LEADS', 'Extern Leads (DO NOT CONTACT)'), ('COMMITTEE_LEADS', 'Committee Leads — ask board before contacting'), ('OTHER', 'Other — ask board before contacting')], max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=astrolink.models.company_logo_path)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lead_professor', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64)),
                ('biography', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=astrolink.models.supervisor_profile_picture_path)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=astrolink.models.casestudy_logo_path)),
                ('description', models.TextField()),
                ('time_estimate', models.CharField(max_length=16)),
                ('revenue_split_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='astrolink.company')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='astrolink.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_estimate', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='astrolink.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('motivation', models.TextField()),
                ('interest', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNHANDLED', 'Not yet handled'), ('INPROGRESS', 'Handling in progress'), ('HANDLED', 'Handled')], default='UNHANDLED', max_length=50)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_study', to='astrolink.casestudy')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='astrolink.project')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='astrolink.supervisor')),
            ],
        ),
    ]
