# Generated by Django 6.0 on 2026-01-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0002_alter_application_member'),
        ('authentication', '0005_alter_supervisorprofile_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='authentication.supervisorprofile'),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
