# Generated by Django 6.0 on 2026-01-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0003_alter_project_supervisor_alter_reference_supervisor_and_more'),
        ('authentication', '0006_studentprofile_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('experience', models.TextField(help_text='Describe your background or experience with this topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='authentication.studentprofile')),
            ],
        ),
    ]
