# Generated by Django 6.0 on 2026-01-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0004_interest'),
        ('authentication', '0008_associationprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='association',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='authentication.associationprofile'),
            preserve_default=False,
        ),
    ]
