# Generated by Django 6.0 on 2026-02-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0005_company_association'),
        ('authentication', '0008_associationprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='association',
            field=models.ForeignKey(blank=True, help_text='Required for general applications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='authentication.associationprofile'),
        ),
    ]
