# Generated by Django 6.0 on 2026-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0007_tag_casestudy_tags_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted by supervisor'), ('REJECTED', 'Rejected by supervisor'), ('CONFIRMED', 'Confirmed by student')], default='PENDING', max_length=50),
        ),
    ]
