# Generated by Django 6.0 on 2026-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0008_application_supervisor_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
