# Generated by Django 6.0 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0010_application_created_at_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System tags cannot be deleted through the UI.'),
        ),
    ]
