# Generated by Django 6.0 on 2026-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0011_tag_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
