# Generated by Django 6.0 on 2026-06-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0014_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
    ]
