# Generated by Django 6.0 on 2026-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0015_remove_attachment_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
