# Generated by Django 6.0 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0016_casestudy_is_open_project_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirmation_deadline_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
