# Generated by Django 6.0 on 2026-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolink', '0017_application_confirmation_deadline_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='close_on_confirm',
            field=models.BooleanField(default=False, help_text='Automatically close the project/case study for applications when the student confirms.'),
        ),
    ]
