# Generated by Django 6.0 on 2026-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_studentprofile_programme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='snumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
