# Generated by Django 6.0 on 2026-01-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_studentprofile_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='pnumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
