# Generated by Django 6.0 on 2026-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_supervisorprofile_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
