# Generated by Django 6.0 on 2026-01-05 21:42

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_associationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.association_profile_picture_path),
        ),
    ]
