# Generated by Django 6.0 on 2026-03-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_associationprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_students', to='authentication.supervisorprofile'),
        ),
    ]
