# Generated by Django 6.0 on 2026-05-31 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_supervisorprofile_academic_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor (BSc)'), ('MASTER', 'Master (MSc)'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='study_programme',
            field=models.CharField(blank=True, choices=[('ASTRONOMY', 'Astronomy'), ('PHYSICS', 'Physics'), ('APPLIED_PHYSICS', 'Applied Physics'), ('OTHER', 'Other')], max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor (BSc)'), ('MASTER', 'Master (MSc)'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('study_programme', models.CharField(blank=True, choices=[('ASTRONOMY', 'Astronomy'), ('PHYSICS', 'Physics'), ('APPLIED_PHYSICS', 'Applied Physics'), ('OTHER', 'Other')], max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
